/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CompanyInfo {
  'gstNumber' : string,
  'state' : string,
  'address' : string,
}
export interface Customer {
  'id' : bigint,
  'gstNumber' : string,
  'name' : string,
  'createdAt' : Time,
  'email' : string,
  'updatedAt' : Time,
  'state' : [] | [string],
  'address' : string,
  'phone' : string,
}
export interface CustomerStatementEntry {
  'transactionType' : { 'sale' : null } |
    { 'payment' : null },
  'date' : Time,
  'description' : string,
  'runningBalance' : bigint,
  'amount' : bigint,
}
export interface FinancialSummary {
  'payments' : Array<Payment>,
  'invoices' : Array<Invoice>,
  'outstandingBalance' : bigint,
}
export interface GstBreakup {
  'taxableAmount' : bigint,
  'cgst' : bigint,
  'igst' : bigint,
  'sgst' : bigint,
  'totalTax' : bigint,
  'totalAmount' : bigint,
}
export interface Invoice {
  'id' : bigint,
  'status' : InvoiceStatus,
  'total' : bigint,
  'createdAt' : Time,
  'updatedAt' : Time,
  'gstBreakups' : Array<GstBreakup>,
  'customerId' : bigint,
  'items' : Array<InvoiceItem>,
}
export interface InvoiceItem {
  'productId' : bigint,
  'quantity' : bigint,
  'price' : bigint,
}
export type InvoiceStatus = { 'pending' : null } |
  { 'paid' : null } |
  { 'overdue' : null };
export interface Payment {
  'id' : bigint,
  'date' : Time,
  'invoiceId' : bigint,
  'amount' : bigint,
}
export interface Product {
  'id' : bigint,
  'sku' : string,
  'name' : string,
  'createdAt' : Time,
  'description' : string,
  'updatedAt' : Time,
  'stock' : bigint,
  'price' : bigint,
  'hsnSacCode' : string,
  'taxRate' : bigint,
}
export interface ShoppingItem {
  'productName' : string,
  'currency' : string,
  'quantity' : bigint,
  'priceInCents' : bigint,
  'productDescription' : string,
}
export interface StripeConfiguration {
  'allowedCountries' : Array<string>,
  'secretKey' : string,
}
export type StripeSessionStatus = {
    'completed' : { 'userPrincipal' : [] | [string], 'response' : string }
  } |
  { 'failed' : { 'error' : string } };
export type Time = bigint;
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface UserProfile {
  'name' : string,
  'businessName' : string,
  'companyInfo' : [] | [CompanyInfo],
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface Vendor {
  'id' : bigint,
  'name' : string,
  'createdAt' : Time,
  'email' : string,
  'updatedAt' : Time,
  'address' : string,
  'phone' : string,
}
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addCustomer' : ActorMethod<
    [string, string, string, string, string, [] | [string]],
    bigint
  >,
  'addInvoice' : ActorMethod<[bigint, Array<InvoiceItem>], bigint>,
  'addProduct' : ActorMethod<
    [string, string, bigint, string, bigint, string, bigint],
    bigint
  >,
  'addVendor' : ActorMethod<[string, string, string, string], bigint>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createCheckoutSession' : ActorMethod<
    [Array<ShoppingItem>, string, string],
    string
  >,
  'deleteCustomer' : ActorMethod<[bigint], undefined>,
  'deleteInvoice' : ActorMethod<[bigint], undefined>,
  'deleteProduct' : ActorMethod<[bigint], undefined>,
  'deleteVendor' : ActorMethod<[bigint], undefined>,
  'findCustomersByName' : ActorMethod<[string], Array<Customer>>,
  'findProductsByName' : ActorMethod<[string], Array<Product>>,
  'findVendorsByName' : ActorMethod<[string], Array<Vendor>>,
  'generateWhatsappMessageLink' : ActorMethod<[string, string], string>,
  'getAllCustomers' : ActorMethod<[], Array<Customer>>,
  'getAllInvoices' : ActorMethod<[], Array<Invoice>>,
  'getAllPayments' : ActorMethod<[], Array<Payment>>,
  'getAllProducts' : ActorMethod<[], Array<Product>>,
  'getAllVendors' : ActorMethod<[], Array<Vendor>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCustomer' : ActorMethod<[bigint], Customer>,
  'getCustomerFinancialSummary' : ActorMethod<[bigint], FinancialSummary>,
  'getCustomerStatement' : ActorMethod<[bigint], Array<CustomerStatementEntry>>,
  'getInvoice' : ActorMethod<[bigint], Invoice>,
  'getProduct' : ActorMethod<[bigint], Product>,
  'getStripeSessionStatus' : ActorMethod<[string], StripeSessionStatus>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getVendor' : ActorMethod<[bigint], Vendor>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isStripeConfigured' : ActorMethod<[], boolean>,
  'recordPayment' : ActorMethod<[bigint, bigint], bigint>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setStripeConfiguration' : ActorMethod<[StripeConfiguration], undefined>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'updateCustomer' : ActorMethod<
    [bigint, string, string, string, string, string, [] | [string]],
    undefined
  >,
  'updateProduct' : ActorMethod<
    [bigint, string, string, bigint, string, bigint, string, bigint],
    undefined
  >,
  'updateVendor' : ActorMethod<
    [bigint, string, string, string, string],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];