/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const InvoiceItem = IDL.Record({
  'productId' : IDL.Nat,
  'quantity' : IDL.Nat,
  'price' : IDL.Int,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ShoppingItem = IDL.Record({
  'productName' : IDL.Text,
  'currency' : IDL.Text,
  'quantity' : IDL.Nat,
  'priceInCents' : IDL.Nat,
  'productDescription' : IDL.Text,
});
export const Time = IDL.Int;
export const Customer = IDL.Record({
  'id' : IDL.Nat,
  'gstNumber' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : Time,
  'email' : IDL.Text,
  'updatedAt' : Time,
  'state' : IDL.Opt(IDL.Text),
  'address' : IDL.Text,
  'phone' : IDL.Text,
});
export const Product = IDL.Record({
  'id' : IDL.Nat,
  'sku' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : Time,
  'description' : IDL.Text,
  'updatedAt' : Time,
  'stock' : IDL.Nat,
  'price' : IDL.Nat,
  'hsnSacCode' : IDL.Text,
  'taxRate' : IDL.Int,
});
export const Vendor = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'createdAt' : Time,
  'email' : IDL.Text,
  'updatedAt' : Time,
  'address' : IDL.Text,
  'phone' : IDL.Text,
});
export const InvoiceStatus = IDL.Variant({
  'pending' : IDL.Null,
  'paid' : IDL.Null,
  'overdue' : IDL.Null,
});
export const GstBreakup = IDL.Record({
  'taxableAmount' : IDL.Int,
  'cgst' : IDL.Int,
  'igst' : IDL.Int,
  'sgst' : IDL.Int,
  'totalTax' : IDL.Int,
  'totalAmount' : IDL.Int,
});
export const Invoice = IDL.Record({
  'id' : IDL.Nat,
  'status' : InvoiceStatus,
  'total' : IDL.Int,
  'createdAt' : Time,
  'updatedAt' : Time,
  'gstBreakups' : IDL.Vec(GstBreakup),
  'customerId' : IDL.Nat,
  'items' : IDL.Vec(InvoiceItem),
});
export const Payment = IDL.Record({
  'id' : IDL.Nat,
  'date' : Time,
  'invoiceId' : IDL.Nat,
  'amount' : IDL.Int,
});
export const CompanyInfo = IDL.Record({
  'gstNumber' : IDL.Text,
  'state' : IDL.Text,
  'address' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'businessName' : IDL.Text,
  'companyInfo' : IDL.Opt(CompanyInfo),
});
export const FinancialSummary = IDL.Record({
  'payments' : IDL.Vec(Payment),
  'invoices' : IDL.Vec(Invoice),
  'outstandingBalance' : IDL.Int,
});
export const CustomerStatementEntry = IDL.Record({
  'transactionType' : IDL.Variant({ 'sale' : IDL.Null, 'payment' : IDL.Null }),
  'date' : Time,
  'description' : IDL.Text,
  'runningBalance' : IDL.Int,
  'amount' : IDL.Int,
});
export const StripeSessionStatus = IDL.Variant({
  'completed' : IDL.Record({
    'userPrincipal' : IDL.Opt(IDL.Text),
    'response' : IDL.Text,
  }),
  'failed' : IDL.Record({ 'error' : IDL.Text }),
});
export const StripeConfiguration = IDL.Record({
  'allowedCountries' : IDL.Vec(IDL.Text),
  'secretKey' : IDL.Text,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addCustomer' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Opt(IDL.Text)],
      [IDL.Nat],
      [],
    ),
  'addInvoice' : IDL.Func([IDL.Nat, IDL.Vec(InvoiceItem)], [IDL.Nat], []),
  'addProduct' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Nat, IDL.Text, IDL.Nat, IDL.Text, IDL.Int],
      [IDL.Nat],
      [],
    ),
  'addVendor' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createCheckoutSession' : IDL.Func(
      [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'deleteCustomer' : IDL.Func([IDL.Nat], [], []),
  'deleteInvoice' : IDL.Func([IDL.Nat], [], []),
  'deleteProduct' : IDL.Func([IDL.Nat], [], []),
  'deleteVendor' : IDL.Func([IDL.Nat], [], []),
  'findCustomersByName' : IDL.Func([IDL.Text], [IDL.Vec(Customer)], ['query']),
  'findProductsByName' : IDL.Func([IDL.Text], [IDL.Vec(Product)], ['query']),
  'findVendorsByName' : IDL.Func([IDL.Text], [IDL.Vec(Vendor)], ['query']),
  'generateWhatsappMessageLink' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Text],
      ['query'],
    ),
  'getAllCustomers' : IDL.Func([], [IDL.Vec(Customer)], ['query']),
  'getAllInvoices' : IDL.Func([], [IDL.Vec(Invoice)], ['query']),
  'getAllPayments' : IDL.Func([], [IDL.Vec(Payment)], ['query']),
  'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getAllVendors' : IDL.Func([], [IDL.Vec(Vendor)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCustomer' : IDL.Func([IDL.Nat], [Customer], ['query']),
  'getCustomerFinancialSummary' : IDL.Func(
      [IDL.Nat],
      [FinancialSummary],
      ['query'],
    ),
  'getCustomerStatement' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(CustomerStatementEntry)],
      ['query'],
    ),
  'getInvoice' : IDL.Func([IDL.Nat], [Invoice], ['query']),
  'getProduct' : IDL.Func([IDL.Nat], [Product], ['query']),
  'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getVendor' : IDL.Func([IDL.Nat], [Vendor], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
  'recordPayment' : IDL.Func([IDL.Nat, IDL.Int], [IDL.Nat], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'updateCustomer' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Opt(IDL.Text),
      ],
      [],
      [],
    ),
  'updateProduct' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        IDL.Text,
        IDL.Nat,
        IDL.Text,
        IDL.Int,
      ],
      [],
      [],
    ),
  'updateVendor' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const InvoiceItem = IDL.Record({
    'productId' : IDL.Nat,
    'quantity' : IDL.Nat,
    'price' : IDL.Int,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ShoppingItem = IDL.Record({
    'productName' : IDL.Text,
    'currency' : IDL.Text,
    'quantity' : IDL.Nat,
    'priceInCents' : IDL.Nat,
    'productDescription' : IDL.Text,
  });
  const Time = IDL.Int;
  const Customer = IDL.Record({
    'id' : IDL.Nat,
    'gstNumber' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : Time,
    'email' : IDL.Text,
    'updatedAt' : Time,
    'state' : IDL.Opt(IDL.Text),
    'address' : IDL.Text,
    'phone' : IDL.Text,
  });
  const Product = IDL.Record({
    'id' : IDL.Nat,
    'sku' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : Time,
    'description' : IDL.Text,
    'updatedAt' : Time,
    'stock' : IDL.Nat,
    'price' : IDL.Nat,
    'hsnSacCode' : IDL.Text,
    'taxRate' : IDL.Int,
  });
  const Vendor = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'createdAt' : Time,
    'email' : IDL.Text,
    'updatedAt' : Time,
    'address' : IDL.Text,
    'phone' : IDL.Text,
  });
  const InvoiceStatus = IDL.Variant({
    'pending' : IDL.Null,
    'paid' : IDL.Null,
    'overdue' : IDL.Null,
  });
  const GstBreakup = IDL.Record({
    'taxableAmount' : IDL.Int,
    'cgst' : IDL.Int,
    'igst' : IDL.Int,
    'sgst' : IDL.Int,
    'totalTax' : IDL.Int,
    'totalAmount' : IDL.Int,
  });
  const Invoice = IDL.Record({
    'id' : IDL.Nat,
    'status' : InvoiceStatus,
    'total' : IDL.Int,
    'createdAt' : Time,
    'updatedAt' : Time,
    'gstBreakups' : IDL.Vec(GstBreakup),
    'customerId' : IDL.Nat,
    'items' : IDL.Vec(InvoiceItem),
  });
  const Payment = IDL.Record({
    'id' : IDL.Nat,
    'date' : Time,
    'invoiceId' : IDL.Nat,
    'amount' : IDL.Int,
  });
  const CompanyInfo = IDL.Record({
    'gstNumber' : IDL.Text,
    'state' : IDL.Text,
    'address' : IDL.Text,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'businessName' : IDL.Text,
    'companyInfo' : IDL.Opt(CompanyInfo),
  });
  const FinancialSummary = IDL.Record({
    'payments' : IDL.Vec(Payment),
    'invoices' : IDL.Vec(Invoice),
    'outstandingBalance' : IDL.Int,
  });
  const CustomerStatementEntry = IDL.Record({
    'transactionType' : IDL.Variant({
      'sale' : IDL.Null,
      'payment' : IDL.Null,
    }),
    'date' : Time,
    'description' : IDL.Text,
    'runningBalance' : IDL.Int,
    'amount' : IDL.Int,
  });
  const StripeSessionStatus = IDL.Variant({
    'completed' : IDL.Record({
      'userPrincipal' : IDL.Opt(IDL.Text),
      'response' : IDL.Text,
    }),
    'failed' : IDL.Record({ 'error' : IDL.Text }),
  });
  const StripeConfiguration = IDL.Record({
    'allowedCountries' : IDL.Vec(IDL.Text),
    'secretKey' : IDL.Text,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addCustomer' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Opt(IDL.Text)],
        [IDL.Nat],
        [],
      ),
    'addInvoice' : IDL.Func([IDL.Nat, IDL.Vec(InvoiceItem)], [IDL.Nat], []),
    'addProduct' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat, IDL.Text, IDL.Nat, IDL.Text, IDL.Int],
        [IDL.Nat],
        [],
      ),
    'addVendor' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createCheckoutSession' : IDL.Func(
        [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'deleteCustomer' : IDL.Func([IDL.Nat], [], []),
    'deleteInvoice' : IDL.Func([IDL.Nat], [], []),
    'deleteProduct' : IDL.Func([IDL.Nat], [], []),
    'deleteVendor' : IDL.Func([IDL.Nat], [], []),
    'findCustomersByName' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Customer)],
        ['query'],
      ),
    'findProductsByName' : IDL.Func([IDL.Text], [IDL.Vec(Product)], ['query']),
    'findVendorsByName' : IDL.Func([IDL.Text], [IDL.Vec(Vendor)], ['query']),
    'generateWhatsappMessageLink' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Text],
        ['query'],
      ),
    'getAllCustomers' : IDL.Func([], [IDL.Vec(Customer)], ['query']),
    'getAllInvoices' : IDL.Func([], [IDL.Vec(Invoice)], ['query']),
    'getAllPayments' : IDL.Func([], [IDL.Vec(Payment)], ['query']),
    'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getAllVendors' : IDL.Func([], [IDL.Vec(Vendor)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCustomer' : IDL.Func([IDL.Nat], [Customer], ['query']),
    'getCustomerFinancialSummary' : IDL.Func(
        [IDL.Nat],
        [FinancialSummary],
        ['query'],
      ),
    'getCustomerStatement' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(CustomerStatementEntry)],
        ['query'],
      ),
    'getInvoice' : IDL.Func([IDL.Nat], [Invoice], ['query']),
    'getProduct' : IDL.Func([IDL.Nat], [Product], ['query']),
    'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getVendor' : IDL.Func([IDL.Nat], [Vendor], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
    'recordPayment' : IDL.Func([IDL.Nat, IDL.Int], [IDL.Nat], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'updateCustomer' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Opt(IDL.Text),
        ],
        [],
        [],
      ),
    'updateProduct' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Text,
          IDL.Nat,
          IDL.Text,
          IDL.Int,
        ],
        [],
        [],
      ),
    'updateVendor' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };